In [15]:
%reload_ext autoreload
%autoreload 2

from Load import *
import numpy as np
import os
import biosignalsnotebooks as bsnb
import sys
import matplotlib.pyplot as plt
module_path = os.path.abspath(os.path.join('C:\\Users\\Rodrigo\\Desktop\\PhD\\1st Study'))
if module_path not in sys.path:
    sys.path.append(module_path)
from Process_Features import *

In [16]:
data, header = pyxdf.load_xdf('G:\\O meu disco\\PhD\\1st Study\\data\\P4_S2_GroupA_eeg.xdf')

In [17]:
Signals,EEG_Signals,marker,timestamps = Load_Data(data)

In [10]:
marker,timestamps = Load_Psychopy(data)
CH1,CH2,CH3,CH4,CH5,CH6,time_Opensignals,fs = Load_Opensignals(data)
EEG_data,time_EEG,EEG_fs = Load_EEG(data)

In [11]:
len(time_Opensignals),len(time_EEG)

(2254624, 480320)

In [18]:
len(marker),len(timestamps)

(52, 52)

In [19]:
onset,offset,videos = getMarkers(marker,timestamps)
len(onset),len(offset)

(26, 26)

In [21]:
onset,EEG_Signals["Time"]

([450.5989211529377,
  731.2459587876219,
  810.6424088137574,
  885.9322619371815,
  967.5557464460144,
  1050.799310364644,
  1134.496962976351,
  1222.9524087370373,
  1309.5017765933299,
  1388.6556891073706,
  1463.072961420694,
  1539.9113051061868,
  1617.1372504766332,
  1694.7578795474255,
  1773.4570353762829,
  1849.6750182484975,
  1925.5783894667402,
  2004.3938537107315,
  2085.791047414008,
  2162.599284258089,
  2239.0627745069796,
  2318.525449444598,
  2400.5665731806657,
  2480.377907666785,
  2558.211687199713,
  2630.6815759004676],
 0          448.478483
 1          448.483175
 2          448.487868
 3          448.492561
 4          448.497254
              ...     
 480315    2702.461110
 480316    2702.465803
 480317    2702.470495
 480318    2702.475188
 480319    2702.479881
 Name: Time, Length: 480320, dtype: float64)

In [22]:
for i in range(0,len(onset)):
    print(np.where(EEG_Signals["Time"] >= onset[i])[0])

[   452    453    454 ... 480317 480318 480319]
[ 60257  60258  60259 ... 480317 480318 480319]
[ 77176  77177  77178 ... 480317 480318 480319]
[ 93220  93221  93222 ... 480317 480318 480319]
[110614 110615 110616 ... 480317 480318 480319]
[128353 128354 128355 ... 480317 480318 480319]
[146188 146189 146190 ... 480317 480318 480319]
[165038 165039 165040 ... 480317 480318 480319]
[183481 183482 183483 ... 480317 480318 480319]
[200349 200350 200351 ... 480317 480318 480319]
[216207 216208 216209 ... 480317 480318 480319]
[232581 232582 232583 ... 480317 480318 480319]
[249037 249038 249039 ... 480317 480318 480319]
[265578 265579 265580 ... 480317 480318 480319]
[282348 282349 282350 ... 480317 480318 480319]
[298590 298591 298592 ... 480317 480318 480319]
[314765 314766 314767 ... 480317 480318 480319]
[331560 331561 331562 ... 480317 480318 480319]
[348905 348906 348907 ... 480317 480318 480319]
[365273 365274 365275 ... 480317 480318 480319]
[381567 381568 381569 ... 480317 480318 

In [40]:
onset_index,offset_index = getMarkersIndex(onset,offset,time_Opensignals)
onset_index_EEG,offset_index_EEG = getMarkersIndex(onset,offset,time_EEG)
offset_index,offset_index_EEG

IndexError: index 0 is out of bounds for axis 0 with size 0

In [33]:
time_Opensignals[13467],time_EEG[3384]

(62832.49393663838, 62832.491011406535)

In [14]:
timestamps-=time_Opensignals[0]
time_Opensignals -= time_Opensignals[0]
time_EEG -= time_EEG[0]

In [10]:
marker

[['baseline', '1'],
 ['baseline', '1'],
 ['EMDB/B/Scenery/5005.avi', '0'],
 ['EMDB/B/Scenery/5005.avi', '1'],
 ['EMDB/B/Scenery/5008.avi', '0'],
 ['EMDB/B/Scenery/5008.avi', '1'],
 ['EMDB/B/Scenery/5007.avi', '0'],
 ['EMDB/B/Scenery/5007.avi', '1'],
 ['EMDB/B/Scenery/5006.avi', '0'],
 ['EMDB/B/Scenery/5006.avi', '1'],
 ['EMDB/B/Scenery/5009.avi', '0'],
 ['EMDB/B/Scenery/5009.avi', '1'],
 ['EMDB/B/Social Negative/3006.avi', '0'],
 ['EMDB/B/Social Negative/3006.avi', '1'],
 ['EMDB/B/Social Negative/3005.avi', '0'],
 ['EMDB/B/Social Negative/3005.avi', '1'],
 ['EMDB/B/Social Negative/3009.avi', '0'],
 ['EMDB/B/Social Negative/3009.avi', '1'],
 ['EMDB/B/Social Negative/3008.avi', '0'],
 ['EMDB/B/Social Negative/3008.avi', '1'],
 ['EMDB/B/Social Negative/3007.avi', '0'],
 ['EMDB/B/Social Negative/3007.avi', '1'],
 ['EMDB/B/Horror/1005.avi', '0'],
 ['EMDB/B/Horror/1005.avi', '1'],
 ['EMDB/B/Horror/1006.avi', '0'],
 ['EMDB/B/Horror/1006.avi', '1'],
 ['EMDB/B/Horror/1007.avi', '0'],
 ['EMDB/B/

In [14]:
timestamps[0]

3.958584532549139

In [11]:
#Opensignals Data Plots
%matplotlib
plt.figure(1)
for timestamp,markers in zip(timestamps,marker):
    if (markers[1] == '1'):
        plt.axvline(x=timestamp,color='r')
    elif(markers[1] == '0'):
        plt.axvline(x=timestamp,color='g')
plt.plot(time_Opensignals,CH1,label="ECG")
plt.plot(time_Opensignals,CH2,label="EDA")
plt.plot(time_Opensignals,CH3,label="RESP")
plt.plot(time_Opensignals,CH4,label="TEMP")
plt.plot(time_Opensignals,CH5,label="fNIRS RED")
plt.plot(time_Opensignals,CH6,label="fNIRS IRED")

# #EEG Data Plots
# plt.figure(2)
# for timestamp,markers in zip(timestamps,marker):
#     if (markers[1] == '1'):
#         plt.axvline(x=timestamp,color='r')
#     elif(markers[1] == '0'):
#         plt.axvline(x=timestamp,color='g')
# for keys in EEG.keys():
#     plt.plot(time_EEG,EEG[keys],label=keys)

Using matplotlib backend: Qt5Agg
